# Instructions:
#
#
# 1. 
# Build the jenkinsserver image using the build-arg docker_gid, example:
# docker-compose build --build-arg docker_gid=$(getent group docker | cut -d: -f3) jenkinsserver
#
# 2.
# Run the jenkinsserver image:
# docker-compose up
#
# 2.
# Follow the instructions in http://localhost/
# to set up jenkins
#
# 3.
# Create a new Pipeline-job and insert some docker code, as an example,
# use the Jenkinsfile in this directory
#
#
version: '3.2'
services:

  jenkinsserver:
    build: ./jenkinsserver
    ports:
      - "80:8080"
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: jenkinsdata
        target: /var/jenkins_home
        volume:
          nocopy: true
    environment:
      JAVA_OPTS: -Duser.timezone=Europe/Stockholm

volumes:
  jenkinsdata:
