version: '2'

services:
    jenkins-master:
        build: jenkins-master
        volumes:
            - jenkins-home:/var/jenkins_home
            - jenkins-log:/var/log/jenkins
            - /var/run/docker.sock:/var/run/docker.sock
            - git-server-keys:/git-server/keys
            - ~/Workspace:/projects:ro
        ports:
            - "80:8080"
    git-server:
        build: git-server
        depends_on:
            - jenkins-master
        ports:
            - "2222:22"
        volumes:
            - git-server-keys:/git-server/keys
            - git-server-repos:/git-server/repos
volumes:
  jenkins-home:
  jenkins-log:
  git-server-keys:
  git-server-repos:
