node() {

    checkout([
            $class                           : "GitSCM",
            branches                         : [[name: "*/$BRANCH_NAME"]],
            doGenerateSubmoduleConfigurations: false,
            extensions                       : [],
            submoduleCfg                     : [],
            userRemoteConfigs                : [[
                                                        credentialsId: "git-credentials",
                                                        url          : "ssh://git@git-server:22/git-server/repos/cicd-workshop-backend"
                                                ]]
    ])

    stage("run tests") {
        docker.image('maven:3.3.3-jdk-8').inside {
            sh 'mvn clean test'
        }
    }

}
